name: Deploy Docker to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/my-nginx-image:latest .
        docker tag your-dockerhub-username/my-nginx-image:latest your-dockerhub-username/my-nginx-image:latest
        docker push your-dockerhub-username/my-nginx-image:latest

    - name: Set up SSH key for EC2 access
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Run Docker commands on EC2
      run: |
        ssh -t -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST_DNS }} << 'EOF'
          # Update and install necessary packages
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce
          sudo systemctl start docker
          sudo systemctl enable docker

          # Verify Docker installation
          docker --version
          sudo systemctl status docker

          # Add ubuntu user to docker group
          sudo usermod -aG docker ubuntu
          newgrp docker

          # Pull the Docker image from Docker Hub
          docker pull your-dockerhub-username/my-nginx-image:latest

          # Stop and remove the existing container (if any)
          docker stop my-container || true
          docker rm my-container || true

          # Run the Docker container
          docker run -d -p 80:80 --name my-container your-dockerhub-username/my-nginx-image:latest
        EOF
